language: node_js
node_js:
  - "0.10"

notifications:
  email:
    - tomas.harkema.1994@gmail.com

services:
  - mongodb

env:
  global:
    - "FTP_USER=deploy"
    - "FTP_PASSWORD=deploy-shit"
after_success:
    "curl --ftp-create-dirs -T . -u $FTP_USER:$FTP_PASSWORD ftp://home.tomasharkema.nl/HomeServer"